[package]
name = "ggez_pixel_canvas"
version = "0.1.12"
edition = "2024"
description = "a helper for drawing in ggez with pixel art"
repository = "https://github.com/AlexMa178/ggez_pixel_canvas"
license = "CC0-1.0"

[dependencies]
generic_discrete_2d_rotations = "0.1.9"
ggez = "0.10.0"
glamour = "0.18.0"
num-traits = "0.2.19"
